### ISSUE TITLE
Background for DISCON-UMaineSemi.IN

### ISSUE THREAD

**Issue by jinch999** [NREL/ROSCO#102]
Hello,

I found that input variables for the controller (DISCON-UMaineSemi.IN) were changed when I compared the version on 4/20/21 with on 06/20/21. Do you have any background for this revision? Should I go with the newest version? Or, is the old version okay? 

Best regards,
Chungkuk Jin

**Comment by nikhar-abbas** [comment]
Hi Chungkuk,
Which DISCON-UMaineSemi.IN file are you referring to? We had a couple different versions of this floating around at one point. I can't remember the exact dates, but those were consolidated the the file in ROSCO [here](https://github.com/NREL/ROSCO/blob/main/Test_Cases/IEA-15-240-RWT-UMaineSemi/ServoData/DISCON-UMaineSemi.IN).

At some point, input variables were changed to account for improvements in the controller and turbine models, and to generally improve the dynamic behavior. That said, I wouldn't expect the resulting controllers to be significantly different in any regard. 

Unless you need to do a comparison to data collected using the older version, I would suggest using the newer one. 
You could also do a quick comparison to see which tuning performs better with the version of ROSCO and turbine model that you are running, depending on what your use case is. 

Best, 
Nikhar
