### ISSUE TITLE
Integral term discrepancy with paper

### ISSUE THREAD

**Issue by ss1870** [NREL/ROSCO#112]
Dear ROSCO developers,

I've been looking through your fortran code and have found there's a small discrepancy between what's in the code and what's stated in the WES paper (A reference open-source controller for fixed and floating offshore wind turbines). The specific function is PIController in Functions.f90.

In the paper, the integral gain is outside of the error integration as in the following equation:
![image](https://user-images.githubusercontent.com/38209284/155651557-873ecc10-3b44-4bf2-aa62-0c20bc1abee8.png)

However, in the code, the integral gain has been effectively placed inside of the error integration, as in this equation:
![image](https://user-images.githubusercontent.com/38209284/155651848-c4d4034d-6cbe-4724-9198-029183c46993.png)
Note that in this equation I quoted the integral gain as a function of pitch angle (beta).

This doesn't make a difference for when the integral gain is constant, but with gain scheduling this makes a noticeable difference. I did a test run and even over 10 seconds of simulation we can see the difference as follows:
![image](https://user-images.githubusercontent.com/38209284/155652358-c1bc3f47-4643-4a34-8d7d-12e1463ed3b8.png)
Please note the pitch angle convention shown in this figure is opposite to normal.

I was wondering which format you think would be more correct?

Kind regards

Sam

**Comment by dzalkind** [comment]
Hi Sam,

Some of our colleagues investigated this in detail here: https://ieeexplore.ieee.org/abstract/document/7525408

From a performance perspective, it effectively decreases the gains, as you've seen.  A better illustration would be to simulate above-rated wind speeds and notice a faster response for the multiply first method.  However, by tuning the ROSCO gains, you can achieve the same performance with both methods.  To answer your question: I think the second equation is technically correct.

I don't think this is necessarily an issue unless it is causing you problems, so I will close this soon and feel free to continue the [discussion here](https://github.com/NREL/ROSCO/discussions).

Best, Dan
