### ISSUE TITLE
FAST.Farm and ROSCO

### ISSUE THREAD

**Issue by Tommi1198** [NREL/ROSCO#118]
Hi everyone,  I encountered this error but I cannot find the file in my computer...how can I fix it? Thanks

At line 77 of file D:\bld\rosco_1615353392809\work\src\ReadSetParameters.f90
Fortran runtime error: Attempting to allocate already allocated variable 'cntrpar'

I have not the D unit on my computer and I don't know how to find this file to fix the problem...what can I do?
Thanks a lot

**Comment by dzalkind** [comment]
Hi there,

Are you using different ROSCO dynamic libraries (DLLs) for each turbine in FAST.Farm?  You'll need to specify it separately in each ServoDyn input.  I don't have a lot of experience with FAST.Farm, but I know we do this with SOWFA.  Asking around for more info.

Not sure about your D:\ drive.  Perhaps some build (D:\bld) program is making that directory.

Dan

**Comment by Tommi1198** [comment]
Dear @dzalkind , I don't know if I'm using the same ROSCO dynamic libraries for each turbine, since I don't know where I can find this information in my files. I tried to use only 1 turbine and the error doesn't showed up...where do I have to specify separately the ROSCO library for each turbine? I cannot found where.
Thanks a lot

**Comment by nikhar-abbas** [comment]
@kshaler, thanks for your quick response here!

Looks to me like this issue is resolved, so I am going to close it.
