### ISSUE TITLE
Issue using TSR tracking control mode

### ISSUE THREAD

**Issue by ElioDaka** [NREL/ROSCO#142]
Dear all,

I am using ROSCO to control a wind turbine model, that is similar to the IEA 15 MW. I have a strange behavior in using TSR tracking control (VS_ControlMode = 2). In particular, in the correspondence of the wind step, I have a large decrease of the generator torque, that goes almost to zero for like 20 seconds, than the torque signal goes to reasonable values. I don't have this problem when using k-w^2 control logic in below rated operations. I am not using the EKF wind estimator but just a filtered wind speed estimate. 
Is this problem related to the controller or to the turbine model? Do you have any suggestion to solve it? 
In the figure below i report generator speed and torque for the two cases.
![TSR_vs_kw2](https://user-images.githubusercontent.com/101867893/172140666-6c234eba-c58c-4400-ad1a-7b1cf57d5122.png)
Thank you
Elio

**Comment by dzalkind** [comment]
Hi Elio,

I generally recommend running `VS_ControlMode = 2` with the wind speed estimator enabled (`WE_Mode` of 1).  When you use the wind speed signal directly with a step input, the tip speed ratio will fall drastically at the step and the torque will drop similarly to track the desired tip speed ratio.  The wind speed estimator provides enough of a time delay that these transients are usually avoided, and it's a more realistic control approach.  Alternatively, you can decrease `F_WECornerFreq` to delay the wind speed estimate signal.

I hope this helps.

Best, Dan

**Comment by ElioDaka** [comment]
Hi Dan,

Thank you very much for your help. Decreasing the frequency of the filter things go much better, the undershoot is still present but is greatly reduced. What I notice is that the dynamic of the system is slower, I mean the rotor reaches a steady state velocity after the wind step in a longer time. I think this is due to the fact that my rotor has a very high inertia, or am I missing something else that can cause this behavior?
Thank you again

Best, Elio

**Comment by nikhar-abbas** [comment]
Hi Elio,

Yes, you are correct - a rotor with high inertia will increase speed more slowly than a rotor with slow inertia. As Dan mentioned, the generator torque may drop to help speed this up, but it can only do so much.

I'm going to move this to the discussions page because it doesn't seem to be an issue with the ROSCO code.

Nikhar
