### ISSUE TITLE
unable to find OL_RAAW.mat

### ISSUE THREAD

**Issue by ncepuyu** [NREL/ROSCO#153]
When I load parameters, OL_RAAW cannot be found.

**Comment by dzalkind** [comment]
Hi,

That file can't be uploaded to GitHub.  It's part of a feature currently under development and was removed from current branches.  Please comment out that part of the code, update your branch, or use `main`/`develop`, and then you will not need that file.  Also, please note that the Simulink version of ROSCO is a learning tool, and the best controller we have for reference and comparison is the Fortran dynamic library.
