### ISSUE TITLE
Output columns without units

### ISSUE THREAD

**Issue by ebranlard** [NREL/ROSCO#180]
Hi,

A user of pyDatView sent me a ".dbg" output file, where some units were missing. 
The columns with missing units were:
       axisTilt_1P axisYaw_1P axisTilt_2P axisYaw_2P YawState       
I've fixed the reader of pyDatView to support missing units, but I think it might be nicer if units are always present (e.g. [NA] or [-]). 

Sorry if that's already been fixed. 

Cheers!

**Comment by dzalkind** [comment]
Thanks for updating pyDatView to support our (potentially faulty) output files!  I'll keep this open and fix the issue.

**Comment by dzalkind** [comment]
Fixed in #188
