### ISSUE TITLE
32 bit DLL ROSCO with Bladed

### ISSUE THREAD

**Issue by Abhi-postdoc** [NREL/ROSCO#193]
Hi Everyone,
I have generated 32-bit.dll for BLADED 4.10 and followed all the steps as mentioned in "https://rosco.readthedocs.io/en/latest/source/ROSCO_instructions_for_Bladed.html". However, I got this error msg in the BLADED interface. Please help me to sort this out.  If possible can you kindly provide any working model of .DLL, and DISCON.IN, .prj file of 5 MW turbine for BLADED to verify where I am doing mistakes. Thanks in advance,

*** Note:   Using legacy controller, 'DISCON' in controller C:\Users\PC00\ROSCO\Test_Cases\NREL-5MW\libdiscon.dll
*** ERROR:   Unknown SEH (Structured Exception Handling) error encountered.  This could be due to using the wrong calling convention being used when calling a dll, or a C++ exception being thrown from within an extern "C" function, or a missing dll dependency encountered in external controller.

_Originally posted by @Abhi-postdoc in https://github.com/NREL/ROSCO/issues/12#issuecomment-1337893875_

**Comment by dzalkind** [comment]
There are 32-bit dlls you should be able to use here: https://github.com/NREL/ROSCO/releases/tag/v2.6.0
