### ISSUE TITLE
Issue in Runnin ROSCO 

### ISSUE THREAD

**Issue by EhsanASL92** [NREL/ROSCO#194]
Hi,

according to some searches, I have just downloaded the ROSCO from this link (https://github.com/dzalkind/matlab-toolbox/tree/master/Simulations) to run in MATLAB.  In the header part of "load_ROSCO_params.m" file it is mentioned that "Uses *.IN file parameters as input via P.SD_dllP  (ServoDyn Dll params)". What should I do in order to load the parameters required for the ROSCO into the work space?

Best regards,
Ehsan

**Comment by dzalkind** [comment]
Hi Ehsan,

I don't think you need to download ROSCO for that link anymore.  You should be able to run [run_FAST.m](https://github.com/NREL/ROSCO/blob/main/Matlab_Toolbox/runFAST.m) and with a few minor changes to the paths, it should find the DISCON.IN parameters for you.

Dan
