### ISSUE TITLE
Warnings in Running ROSCO

### ISSUE THREAD

**Issue by lqw075** [NREL/ROSCO#195]
Hi,
When I run ROSCO-2.5.0, I get these two kinds of warnings:
Firstly:
"'input port 1' of 'ROSCO/BldPitch Controller/Mux' is not connected"

Secondly:
"If the inport ROSCO/Cyclic Pitch controller/1P Cyclic Pitch Controller1/PI - Q/Mq of subsystem 'ROSCO/Cyclic Pitch
controller/1P Cyclic Pitch Controller1/PI - Q' involves direct feedback, then an algebraic loop exists, which Simulink
cannot remove. To avoid this warning, consider clearing the 'Minimize algebraic loop occurrences' parameter of the subsystem
or set the Algebraic loop diagnostic to 'none' in the Diagnostics tab of the Configuration Parameters dialog. "

I want to know how to solve them, how much impact do they have.
Best regards,

**Comment by dzalkind** [comment]
You can safely ignore these warnings.
