### ISSUE TITLE
PA_Mode 1 not working

### ISSUE THREAD

**Issue by pelljam** [NREL/ROSCO#212]
Hi, 

You can't use PA_Mode 1.

If you look in ReadSetParameters.f90, you validate the data like this:

`        ! --- Pitch Actuator ---
        IF (CntrPar%PA_Mode > 0) THEN
            IF ((CntrPar%PA_Mode < 0) .OR. (CntrPar%PA_Mode < 2)) THEN
                ErrVar%aviFAIL = -1
                ErrVar%ErrMsg = 'PA_Mode must be 0, 1, or 2'
            END IF`
    
I suspect you meant to test `CntrPar%PA_Mode > 2`

Hope this helps, 

James P

**Comment by dzalkind** [comment]
Yep, good catch.  I always use `PA_Mode` of 2, so it slipped by the check.  #213 will fix this issue.
