### ISSUE TITLE
I get this error when running ROSCO，"Error reported by S-function 'FAST_SFunc' in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function':"

### ISSUE THREAD

**Issue by SYZ622** [NREL/ROSCO#225]
I am using openfast version 3.0.0, ROSCO2.4.1 and after running it, I get the following error

Error reported by S-function 'FAST_SFunc' in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function':
FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:Invalid logical input for file "D:\Users\999\Desktop\openfast\5MW_OC3Mnpl_DLL_WTurb_WavesIrr\5MW_OC3Mnpl_DLL_WTurb_WavesIrr.fst" occurred while trying to read SumPrint.

I don't know how to solve the Error. Hope to get some help, thanks!!!

**Comment by dzalkind** [comment]
This looks like an issue with the input file version.  You must use a set of OpenFAST inputs corresponding to your OpenFAST version.  Closing because this does not sound like a ROSCO issue.
