### ISSUE TITLE
Numpy 'warnings'

### ISSUE THREAD

**Issue by Yuksel-Rudy** [NREL/ROSCO#240]
I've been trying to compile the new version of ROSCO v.2.8.0 but I'm having a bit of a trouble with this version. I'm not sure if it is a bug or I am missing something. But after a long investigation, I was able to compile everything as normal when I install wisdem without specifying the version: `conda install -y wisdem` but if I go with the documentation and specify the 3.5 version (i.e `conda install -y wisdem=3.5.0`) I get the following error if I try to run any of the examples:

```
Traceback (most recent call last):
  File "01_turbine_model.py", line 18, in <module>
    from ROSCO_toolbox import turbine as ROSCO_turbine
  File "/home/rudy/anaconda3/envs/rosco-env/lib/python3.8/site-packages/rosco-2.7.0-py3.8-linux-x86_64.egg/ROSCO_toolbox/turbine.py", line 21, in <module>
    from ROSCO_toolbox.utilities import load_from_txt
  File "/home/rudy/anaconda3/envs/rosco-env/lib/python3.8/site-packages/rosco-2.7.0-py3.8-linux-x86_64.egg/ROSCO_toolbox/utilities.py", line 30, in <module>
    from wisdem.inputs import load_yaml
  File "/home/rudy/anaconda3/envs/rosco-env/lib/python3.8/site-packages/wisdem/__init__.py", line 1, in <module>
    from wisdem.glue_code.runWISDEM import run_wisdem
  File "/home/rudy/anaconda3/envs/rosco-env/lib/python3.8/site-packages/wisdem/glue_code/runWISDEM.py", line 15, in <module>
    np.warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
  File "/home/rudy/anaconda3/envs/rosco-env/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'
```

I can go without specifying the version but I feel this is not what is intended because if I go ahead and install openfast and try to run an openfast example (example 5 for instance), it will abort due to incompatibility issue (with the inflow input file) I can have a workaround this by modifying this but if I want everything to be up-to-date, I need to solve the above error. 

Here are the steps to replicate the error:

```
conda config --add channels conda-forge
conda create -y --name rosco-env python=3.8
conda activate rosco-env
git clone https://github.com/NREL/ROSCO.git
cd ROSCO
conda install compilers
conda install -y wisdem=3.5.0 # (without =3.5.0 will not lead to error)
python setup.py install --compile-rosco
conda install -c conda-forge zeromq # because I want to compile with zmq
conda install -c conda-forge pyzmq  # because I want to compile with zmq
cd ROSCO
rm -r build install
mkdir build
cd build
cmake -DZMQ_CLIENT=ON ..
make install
conda install -c conda-forge openfast
```

Numpy depreciated ‘warnings’ at some point recently. But I am not sure why the new version of wisdem generates the above error.

**Comment by dzalkind** [comment]
Hi Rudy,

WISDEM 3.5.0 is not the latest, and this documentation should be updated to reflect the latest version of WISDEM that works with the latest version of `numpy`.

I think that the documentation line should say:
`conda install -y wisdem>3.7` 

Thanks for bringing this to our attention and using the latest tools! I'll keep this open until we update the docs.

Best, Dan

**Comment by dzalkind** [comment]
I have updated the docs in #241

**Comment by windpower2023** [comment]
Hi Dan,

I have the fresh installation on Windows git cmd and also tried on wsl on window machine I get same error.

On window machine..I followed these steps:

I have used **git cmd** or **git bash** terminal

- conda config --add channels conda-forge
- conda create -y --name rosco-env python=3.8
- conda activate rosco-env
- copy and paste source code from git for ROSCO 2.8   (instead of **git clone https://github.com/NREL/ROSCO.git**)
- cd ROSCO
- conda install m2w64-toolchain libpython
- conda env config vars set FC=gfortran
- conda install -y wisdem
- python setup.py install --compile-rosco

**Comment by windpower2023** [comment]
conda install -y wisdem>3.7
python setup.py install

**Comment by dzalkind** [comment]
What is the output to your terminal when you do `python setup.py install`?

**Comment by windpower2023** [comment]
running install                                                                                                                   C:\Users\RameshKumar\anaconda3\envs\rosco-env\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.                                                                                                      !!                                                                                                                                                                                                                                                                          ********************************************************************************                                                  Please avoid running ``setup.py`` directly.                                                                                       Instead, use pypa/build, pypa/installer or other                                                                                  standards-based tools.                                                                                                                                                                                                                                              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.                                                ********************************************************************************                                                                                                                                                                            !!                                                                                                                                  self.initialize_options()                                                                                                       C:\Users\RameshKumar\anaconda3\envs\rosco-env\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.                                                                                                 !!                                                                                                                                                                                                                                                                          ********************************************************************************                                                  Please avoid running ``setup.py`` and ``easy_install``.                                                                           Instead, use pypa/build, pypa/installer or other                                                                                  standards-based tools.                                                                                                                                                                                                                                              See https://github.com/pypa/setuptools/issues/917 for details.                                                                    ********************************************************************************                                                                                                                                                                            !!                                                                                                                                  self.initialize_options()                                                                                                       running bdist_egg                                                                                                                 running egg_info                                                                                                                  writing rosco.egg-info\PKG-INFO                                                                                                   writing dependency_links to rosco.egg-info\dependency_links.txt                                                                   writing requirements to rosco.egg-info\requires.txt                                                                               writing top-level names to rosco.egg-info\top_level.txt                                                                           reading manifest file 'rosco.egg-info\SOURCES.txt'                                                                                adding license file 'LICENSE'                                                                                                     writing manifest file 'rosco.egg-info\SOURCES.txt'                                                                                installing library code to build\bdist.win-amd64\egg                                                                              running install_lib                                                                                                               running build_py                                                                                                                  creating build\bdist.win-amd64\egg                                                                                                creating build\bdist.win-amd64\egg\ROSCO_testing                                                                                  copying build\lib\ROSCO_testing\ROSCO_testing.py -> build\bdist.win-amd64\egg\ROSCO_testing                                       copying build\lib\ROSCO_testing\run_Testing.py -> build\bdist.win-amd64\egg\ROSCO_testing                                         copying build\lib\ROSCO_testing\test_checkpoint.py -> build\bdist.win-amd64\egg\ROSCO_testing                                     copying build\lib\ROSCO_testing\__init__.py -> build\bdist.win-amd64\egg\ROSCO_testing                                            creating build\bdist.win-amd64\egg\ROSCO_toolbox                                                                                  copying build\lib\ROSCO_toolbox\controller.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                          copying build\lib\ROSCO_toolbox\control_interface.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                   creating build\bdist.win-amd64\egg\ROSCO_toolbox\inputs                                                                           copying build\lib\ROSCO_toolbox\inputs\schema2rst.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\inputs                            copying build\lib\ROSCO_toolbox\inputs\toolbox_schema.yaml -> build\bdist.win-amd64\egg\ROSCO_toolbox\inputs                      copying build\lib\ROSCO_toolbox\inputs\validation.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\inputs                            copying build\lib\ROSCO_toolbox\inputs\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\inputs                              creating build\bdist.win-amd64\egg\ROSCO_toolbox\linear                                                                           copying build\lib\ROSCO_toolbox\linear\linear_models.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\linear                         copying build\lib\ROSCO_toolbox\linear\lin_util.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\linear                              copying build\lib\ROSCO_toolbox\linear\lin_vis.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\linear                               copying build\lib\ROSCO_toolbox\linear\robust_scheduling.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\linear                     copying build\lib\ROSCO_toolbox\linear\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\linear                              creating build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools                                                                          creating build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen                                                                 copying build\lib\ROSCO_toolbox\ofTools\case_gen\CaseGen_General.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen   copying build\lib\ROSCO_toolbox\ofTools\case_gen\CaseGen_IEC.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen       copying build\lib\ROSCO_toolbox\ofTools\case_gen\CaseLibrary.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen       copying build\lib\ROSCO_toolbox\ofTools\case_gen\HH_WindFile.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen       copying build\lib\ROSCO_toolbox\ofTools\case_gen\runFAST_pywrapper.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen copying build\lib\ROSCO_toolbox\ofTools\case_gen\run_FAST.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen          copying build\lib\ROSCO_toolbox\ofTools\case_gen\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen          creating build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io                                                                  copying build\lib\ROSCO_toolbox\ofTools\fast_io\FAST_post.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io           copying build\lib\ROSCO_toolbox\ofTools\fast_io\FAST_reader.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io         copying build\lib\ROSCO_toolbox\ofTools\fast_io\FAST_vars.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io           copying build\lib\ROSCO_toolbox\ofTools\fast_io\FAST_vars_out.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io       copying build\lib\ROSCO_toolbox\ofTools\fast_io\FAST_wrapper.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io        copying build\lib\ROSCO_toolbox\ofTools\fast_io\FAST_writer.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io         copying build\lib\ROSCO_toolbox\ofTools\fast_io\file.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io                copying build\lib\ROSCO_toolbox\ofTools\fast_io\output_processing.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io   copying build\lib\ROSCO_toolbox\ofTools\fast_io\pyIECWind.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io           creating build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                       copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_reader.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                                  copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_vartrees.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                                copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_wrapper.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                                 copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_writer.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                                  copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbulence_spectrum.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                             copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\wind_profile_writer.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                             copying build\lib\ROSCO_toolbox\ofTools\fast_io\turbsim_io\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io                                                                                                                        copying build\lib\ROSCO_toolbox\ofTools\fast_io\update_discons.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io      copying build\lib\ROSCO_toolbox\ofTools\fast_io\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io            creating build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util                                                                     copying build\lib\ROSCO_toolbox\ofTools\util\FileTools.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util                 copying build\lib\ROSCO_toolbox\ofTools\util\spectral.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util                  copying build\lib\ROSCO_toolbox\ofTools\util\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util                  copying build\lib\ROSCO_toolbox\ofTools\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools                            copying build\lib\ROSCO_toolbox\sim.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                                 copying build\lib\ROSCO_toolbox\tune.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                                copying build\lib\ROSCO_toolbox\turbine.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                             copying build\lib\ROSCO_toolbox\utilities.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                           copying build\lib\ROSCO_toolbox\__init__.py -> build\bdist.win-amd64\egg\ROSCO_toolbox                                            byte-compiling build\bdist.win-amd64\egg\ROSCO_testing\ROSCO_testing.py to ROSCO_testing.cpython-38.pyc                           byte-compiling build\bdist.win-amd64\egg\ROSCO_testing\run_Testing.py to run_Testing.cpython-38.pyc                               byte-compiling build\bdist.win-amd64\egg\ROSCO_testing\test_checkpoint.py to test_checkpoint.cpython-38.pyc                       byte-compiling build\bdist.win-amd64\egg\ROSCO_testing\__init__.py to __init__.cpython-38.pyc                                     byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\controller.py to controller.cpython-38.pyc                                 byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\control_interface.py to control_interface.cpython-38.pyc                   byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\inputs\schema2rst.py to schema2rst.cpython-38.pyc                          byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\inputs\validation.py to validation.cpython-38.pyc                          byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\inputs\__init__.py to __init__.cpython-38.pyc                              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\linear\linear_models.py to linear_models.cpython-38.pyc                    byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\linear\lin_util.py to lin_util.cpython-38.pyc                              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\linear\lin_vis.py to lin_vis.cpython-38.pyc                                byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\linear\robust_scheduling.py to robust_scheduling.cpython-38.pyc            byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\linear\__init__.py to __init__.cpython-38.pyc                              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\CaseGen_General.py to CaseGen_General.cpython-38.pyc      byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\CaseGen_IEC.py to CaseGen_IEC.cpython-38.pyc              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\CaseLibrary.py to CaseLibrary.cpython-38.pyc              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\HH_WindFile.py to HH_WindFile.cpython-38.pyc              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\runFAST_pywrapper.py to runFAST_pywrapper.cpython-38.pyc  byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\run_FAST.py to run_FAST.cpython-38.pyc                    byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\case_gen\__init__.py to __init__.cpython-38.pyc                    byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\FAST_post.py to FAST_post.cpython-38.pyc                   byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\FAST_reader.py to FAST_reader.cpython-38.pyc               byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\FAST_vars.py to FAST_vars.cpython-38.pyc                   byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\FAST_vars_out.py to FAST_vars_out.cpython-38.pyc           byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\FAST_wrapper.py to FAST_wrapper.cpython-38.pyc             byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\FAST_writer.py to FAST_writer.cpython-38.pyc               byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\file.py to file.cpython-38.pyc                             byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\output_processing.py to output_processing.cpython-38.pyc   byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\pyIECWind.py to pyIECWind.cpython-38.pyc                   byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_reader.py to turbsim_reader.cpython-38.pyc                                                                                                                                byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_vartrees.py to turbsim_vartrees.cpython-38.pyc                                                                                                                            byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_wrapper.py to turbsim_wrapper.cpython-38.pyc                                                                                                                              byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbsim_writer.py to turbsim_writer.cpython-38.pyc                                                                                                                                byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\turbulence_spectrum.py to turbulence_spectrum.cpython-38.pyc                                                                                                                      byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\wind_profile_writer.py to wind_profile_writer.cpython-38.pyc                                                                                                                      byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\turbsim_io\__init__.py to __init__.cpython-38.pyc          byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\update_discons.py to update_discons.cpython-38.pyc         byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\fast_io\__init__.py to __init__.cpython-38.pyc                     byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util\FileTools.py to FileTools.cpython-38.pyc                      byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util\spectral.py to spectral.cpython-38.pyc                        byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\util\__init__.py to __init__.cpython-38.pyc                        byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\ofTools\__init__.py to __init__.cpython-38.pyc                             byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\sim.py to sim.cpython-38.pyc                                               byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\tune.py to tune.cpython-38.pyc                                             byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\turbine.py to turbine.cpython-38.pyc                                       byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\utilities.py to utilities.cpython-38.pyc                                   byte-compiling build\bdist.win-amd64\egg\ROSCO_toolbox\__init__.py to __init__.cpython-38.pyc                                     creating build\bdist.win-amd64\egg\EGG-INFO                                                                                       copying rosco.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO                                                             copying rosco.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO                                                          copying rosco.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO                                                 copying rosco.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO                                                         copying rosco.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO                                                         copying rosco.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO                                                        creating 'dist\rosco-2.7.0-py3.8.egg' and adding 'build\bdist.win-amd64\egg' to it                                                removing 'build\bdist.win-amd64\egg' (and everything under it)                                                                    Processing rosco-2.7.0-py3.8.egg                                                                                                  removing 'c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages\rosco-2.7.0-py3.8.egg' (and everything under it)        creating c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages\rosco-2.7.0-py3.8.egg                                    Extracting rosco-2.7.0-py3.8.egg to c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                               Adding rosco 2.7.0 to easy-install.pth file                                                                                                                                                                                                                         Installed c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages\rosco-2.7.0-py3.8.egg                                   Processing dependencies for rosco==2.7.0                                                                                          Searching for pandas==2.0.3                                                                                                       Best match: pandas 2.0.3                                                                                                          Adding pandas 2.0.3 to easy-install.pth file                                                                                                                                                                                                                        Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for PyYAML==6.0.1                                                                                                       Best match: PyYAML 6.0.1                                                                                                          Adding PyYAML 6.0.1 to easy-install.pth file                                                                                                                                                                                                                        Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for scipy==1.10.1                                                                                                       Best match: scipy 1.10.1                                                                                                          Adding scipy 1.10.1 to easy-install.pth file                                                                                                                                                                                                                        Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for numpy==1.24.4                                                                                                       Best match: numpy 1.24.4                                                                                                          Adding numpy 1.24.4 to easy-install.pth file                                                                                      Installing f2py-script.py script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                         Installing f2py.exe script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                                                                                                                                                                 Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for matplotlib==3.7.3                                                                                                   Best match: matplotlib 3.7.3                                                                                                      Adding matplotlib 3.7.3 to easy-install.pth file                                                                                                                                                                                                                    Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for tzdata==2023.4                                                                                                      Best match: tzdata 2023.4                                                                                                         Adding tzdata 2023.4 to easy-install.pth file                                                                                                                                                                                                                       Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for pytz==2023.3.post1                                                                                                  Best match: pytz 2023.3.post1                                                                                                     Adding pytz 2023.3.post1 to easy-install.pth file                                                                                                                                                                                                                   Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for python-dateutil==2.8.2                                                                                              Best match: python-dateutil 2.8.2                                                                                                 Adding python-dateutil 2.8.2 to easy-install.pth file                                                                                                                                                                                                               Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for importlib-resources==6.1.1                                                                                          Best match: importlib-resources 6.1.1                                                                                             Adding importlib-resources 6.1.1 to easy-install.pth file                                                                                                                                                                                                           Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for pyparsing==3.1.1                                                                                                    Best match: pyparsing 3.1.1                                                                                                       Adding pyparsing 3.1.1 to easy-install.pth file                                                                                                                                                                                                                     Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for Pillow==10.0.1                                                                                                      Best match: Pillow 10.0.1                                                                                                         Adding Pillow 10.0.1 to easy-install.pth file                                                                                                                                                                                                                       Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for packaging==23.2                                                                                                     Best match: packaging 23.2                                                                                                        Adding packaging 23.2 to easy-install.pth file                                                                                                                                                                                                                      Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for kiwisolver==1.4.5                                                                                                   Best match: kiwisolver 1.4.5                                                                                                      Adding kiwisolver 1.4.5 to easy-install.pth file                                                                                                                                                                                                                    Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for fonttools==4.47.2                                                                                                   Best match: fonttools 4.47.2                                                                                                      Adding fonttools 4.47.2 to easy-install.pth file                                                                                  Installing fonttools-script.py script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                    Installing fonttools.exe script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                          Installing pyftmerge-script.py script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                    Installing pyftmerge.exe script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                          Installing pyftsubset-script.py script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                   Installing pyftsubset.exe script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                         Installing ttx-script.py script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                          Installing ttx.exe script to C:\Users\RameshKumar\anaconda3\envs\rosco-env\Scripts                                                                                                                                                                                  Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for cycler==0.12.1                                                                                                      Best match: cycler 0.12.1                                                                                                         Adding cycler 0.12.1 to easy-install.pth file                                                                                                                                                                                                                       Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for contourpy==1.1.1                                                                                                    Best match: contourpy 1.1.1                                                                                                       Adding contourpy 1.1.1 to easy-install.pth file                                                                                                                                                                                                                     Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for six==1.16.0                                                                                                         Best match: six 1.16.0                                                                                                            Adding six 1.16.0 to easy-install.pth file                                                                                                                                                                                                                          Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Searching for zipp==3.17.0                                                                                                        Best match: zipp 3.17.0                                                                                                           Adding zipp 3.17.0 to easy-install.pth file                                                                                                                                                                                                                         Using c:\users\rameshkumar\anaconda3\envs\rosco-env\lib\site-packages                                                             Finished processing dependencies for rosco==2.7.0                                                                                                                                                                                                                   (rosco-env) C:\Users\RameshKumar\ROSCO>

**Comment by dzalkind** [comment]
Are you sure you're using the latest version of the `main` branch?

Can you try with a fresh environment and using `python setup.py develop` instead?

**Comment by windpower2023** [comment]
![image](https://github.com/NREL/ROSCO/assets/131686893/e6704216-40d6-43be-896c-a4a997bb8f82)
Running all these steps in Anaconda power script  worked...

Apologies does it has to be only in Anaconda Powershell script cmd?
