### ISSUE TITLE
Wrong check for F_NotchType's value

### ISSUE THREAD

**Issue by R-Quancard** [NREL/ROSCO#247]
Hello,
I've noticed that mode 3 of F_NotchType could not be used because CheckInputs only allows 0, 1 or 2. Actually, the suitable check is there (allowing 0 to 3) but an additional one blocks the case F_NotchType = 3, so that second one should be removed.

https://github.com/NREL/ROSCO/blob/e3b7db779ad9e7bea5dea692e92f52b10116cf02/ROSCO/src/ReadSetParameters.f90#L735-L745

**Comment by dzalkind** [comment]
Good catch...thanks!

I have pushed a change to #246.

Best, Dan

**Comment by dzalkind** [comment]
This should be in the develop branch now.
