### ISSUE TITLE
Power optimization issue in develop branch for below nominal wind speed

### ISSUE THREAD

**Issue by PE-Meunier** [NREL/ROSCO#26]
When using the develop branch, I get significantly lower power (GenPwr) than when using the master branch. This comparison has been performed using the same discon file and rotor performance file.

**Comment by nikhar-abbas** [comment]
This sounds like it might be related to your previously submitted issue #25.

Can you provide a plot or two showing what's going on here? Hopefully then I can try to re-create the error on my end. 

Also, same question as in #25, are you on the most recent version of the Master branch (v2.1.0), or the previous release (v2.0.3)?

**Comment by PE-Meunier** [comment]
I agree with you. The wind estimation error could be the cause of this behavior. Please find below some graph with wind velocity around 7m/s. The black line in the genPower part of the graph represents the expected power at this wind velocity (which was reached with the older version of fast "8a5fef005f383a1c45da435ae4283dc1e7c2a1e3").

![image](https://user-images.githubusercontent.com/71760505/94142339-6ace8b00-fe6e-11ea-8de6-7efb9c3fef9f.png)
