### ISSUE TITLE
How to get the DISCON.IN file

### ISSUE THREAD

**Issue by Tomedssa** [NREL/ROSCO#276]
Hi,
IN ROSCO's test case, I found the "DISCON.IN" file for the 5MW onshore wind turbine, but not for the 5WM offshore floating wind turbine. Can I obtain the "DISCON.IN" file for the 5WM Offshore floating wind turbine by modifying the "DISCON.IN" file for the 5WM onshore wind turbine? Or do I need to compile some code to get the "DISCON.IN" file for the 5WM offshore floating wind turbine?
Thank you very much for your time in advance.

**Comment by dzalkind** [comment]
Hi, DISCON.IN files do not need to be compiled; they are text files.  Please see the documentation for more info about how DISCON files are generated: https://rosco.readthedocs.io/en/latest/source/standard_use.html
