### ISSUE TITLE
Installation bugs with zeromq mode

### ISSUE THREAD

**Issue by abhineet-gupta** [NREL/ROSCO#296]
DRAFT (Confirm with a fresh installation and add instructions for duplication):

Found a couple of bugs with ROSCO installation with ZeroMQ mode enabled.
 - Add a zeromq option for instructions in [full rosco installtion](https://rosco.readthedocs.io/en/latest/source/install.html#full-rosco-installation) as `python setup.py install --compile-rosco` does not compile with zeromq.
 - If ROSCO toolbox is installed using `python setup.py install`, the toolbox is not able to find `wfc_interface.yaml`. However, it finds the file if ROSCO toolbox is installed using `python setup.py develop`.

**Comment by dzalkind** [comment]
PR #294 may simplify the `install` and `--compile-rosco`, so I'd recommend starting there.  It works right now for `python setup.py develop`.
