### ISSUE TITLE
Segmentation fault in ROSCO while restarting openfast with checkpoint

### ISSUE THREAD

**Issue by ramisetti** [NREL/ROSCO#31]
I am trying to use ROSCO for the IEA 15MW semisubmersible case with openfast v2.4.0 with the restart option after the checkpoint file is generated in the first run. I found openfast is aborting due to some segmentation fault arising in ROSCO code (see below). I think there may be some memory problem with the "interp1d" function inside the Functions.f90. I have used the latest code (17 Nov 2020) from ROSCO repo on GitHub. can you please help me fix this issue?

**************************************************************************************************
 OpenFAST

 Copyright (C) 2020 National Renewable Energy Laboratory
 Copyright (C) 2020 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.4.0
 Compile Info:
  - Compiler: GCC version 7.1.0
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 17 2020
  - Time: 10:04:53
 Execution Info:
  - Date: 11/17/2020
  - Time: 17:16:07+0530

  Restarting simulation at 5 seconds.

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7ff66cac92ef in ???
#1  0x7ff66c18fa87 in __functions_MOD_interp1d
	at /soft/opensoft/ROSCO/src/Functions.f90:170
#2  0x7ff66c18d63c in __controllers_MOD_pitchcontrol
	at /soft/opensoft/ROSCO/src/Controllers.f90:63
#3  0x7ff66c18dce5 in DISCON
	at /soft/opensoft/ROSCO/src/DISCON.F90:74
#4  0x1099c06 in ???
#5  0x1099cd3 in ???
#6  0x1099f60 in ???
#7  0x109b958 in ???
#8  0x10a357b in ???
#9  0x8706b5 in ???
#10  0x5892c7 in ???
#11  0x58abdc in ???
#12  0x524686 in ???
#13  0x4162fe in ???
#14  0x7ff66cab5444 in ???
#15  0x41632e in ???
#16  0xffffffffffffffff in ???
Segmentation fault (core dumped)

**Comment by nikhar-abbas** [comment]
Hi @ramisetti,
Unfortunately, we do not have any restart capabilities included in ROSCO right now. I'm going to leave this github issue open until it is resolved. As it is now, we don't have any specific plans to include this feature, but will certainly add it to the docket as "nice to have" items as we continue our development. 

Of course, if this is a capability that you feel qualified to contribute, we would encourage that!

Thanks,
Nikhar
