### ISSUE TITLE
pip install -e . not working as intended on Windows

### ISSUE THREAD

**Issue by AdrianEolion** [NREL/ROSCO#332]
Hi,

I have followed all the steps to install ROSCO 2.9.0 on Windows, but it seems like the installation is not done properly.
After installation I get the error "**_DLL load failed while importing __precomp_**" while running the example 01. I don't know if I am missing something.

Any help would be greatly appreciated. 
Thanks

**Comment by dzalkind** [comment]
This is a known issue in WISDEM: https://github.com/WISDEM/WISDEM/issues/505

Please re-try with an older version of wisdem: `conda install wisdem=3.13`

**Comment by AdrianEolion** [comment]
Now it does work. 

Thanks you very much!
