### ISSUE TITLE
Invalid tag on 2.9.1?

### ISSUE THREAD

**Issue by marchdf** [NREL/ROSCO#337]
I noticed that the tag on 2.9.1 is `v.2.9.1` (https://github.com/NREL/ROSCO/releases/tag/v.2.9.1) and does not follow all the other tagging conventions in this repo (e.g. v2.9.0, https://github.com/NREL/ROSCO/releases/tag/v2.9.0). Basically, I think it should be `v2.9.1` and not `v.2.9.1` (spurious period after the `v`). Unless this was intentional?

**Comment by abhineet-gupta** [comment]
Thanks for bringing attention to this. We will get back on this by next week.

**Comment by dzalkind** [comment]
I updated this tag.  A new version (v2.9.2) should have your compiler fixes @marchdf
