### ISSUE TITLE
add wintypes to the ctypes import

### ISSUE THREAD

**Issue by rdamiani** [NREL/ROSCO#350]
Using the internal simulator in the toolbox on win64, it bombs on line 256 of `control_interface.py`

 `dlclose = lambda handle: 0 if _dlclose(handle) else 1`

fixed following this: https://bugs.python.org/issue30286

`ctypes.windll.kernel32.FreeLibrary.argtypes = [wintypes.HMODULE]  #RRD added` 
and importing wintypes in the ctypes import.

check my fork if useful, and can close this. 
Thx.

**Comment by dzalkind** [comment]
Thanks for the update, @rdamiani.  Can you provide a link to your suggested fix?

**Comment by rdamiani** [comment]
https://github.com/rdamiani/ROSCO/commit/e59b7ac901532b2cd1e1b82a1f924fd420c71911
hopefully this works
