### ISSUE TITLE
WE_Mode setting 2

### ISSUE THREAD

**Issue by amineeva-GWT** [NREL/ROSCO#360]
## Description
I'm in the process of learning more about ROSCO with a goal of generating a data for a simple wind ramp diagram. As I was going through the mode variables in the ROSCO tuning parameters, I noticed that parameter WE_Mode was set to 2, but I'm not sure what this means/why it's set to 2 since that doesn't seem to be an option:
![image](https://github.com/NREL/ROSCO/assets/170118494/7586e9ec-35c8-4bfe-9e67-139a1998fb7f)
Source: https://rosco.readthedocs.io/en/latest/source/toolbox_input.html

This is the specific file I was looking at (WE_Mode is on line 36): https://github.com/NREL/ROSCO/blob/main/Examples/Tune_Cases/NREL5MW.yaml 

I saw some other issues in this repo refer to setting 2 as a Kalman filter, but would like confirmation:
https://github.com/NREL/ROSCO/issues/25
https://github.com/NREL/ROSCO/issues/53
- As per issue 53, it also seems like the Kalman filter may not have been working properly - has it been updated since?

**Comment by dzalkind** [comment]
I updated the documentation in a docs branch.  Please refer to the DISCON comments in the meantime: https://github.com/NREL/ROSCO/blob/8b85d7a923b5c2fd99f2178276304fa5ce0d18df/Examples/Test_Cases/IEA-15-240-RWT-UMaineSemi/DISCON-UMaineSemi.IN#L19

The issues cited have been closed.  The EKF is the preferred wind speed estimator.
