### ISSUE TITLE
Max torque rate for the 5 MW 

### ISSUE THREAD

**Issue by MaximilienAndre** [NREL/ROSCO#362]
Dear all, 

I have a quick question regarding the max rated torque for the 5MW wind turbine. 

In the source .yaml files to parametrize the controler for the 5MW `Examples/Tune_Cases/NREL5MW.yaml` we acan read 

`  max_torque_rate:    1500000.              # Maximum torque rate [Nm/s], {~1/4 VS_RtTq/s}`

I understand that this is the maximum torque rate for the generator and that you recommand using 1/4 th of the rated torque for this value. However, if my understanding is correct, we should use the rated torque at the HSS and according to the 5MW reference paper (Jonkman 2009) this value is approximately equal to 43000 N.m. Was the gearbox not taken in consideration for this computation ? 

Best regards, 

Maximilien

**Comment by MaximilienAndre** [comment]
Dear @dzalkind , I have seen that you have modified the torque in the fix_scipy branch for the NREL-5MW, yet I still don't understand your value. 

My understanding is that according to 5MW reference paper (Jonkman2009) the rated generator torque is 43000 N.m , so following the comment that says "~1/4 Vs_RtTq". I identifited Vs_RtTq with the line 29 in ServoDyn file that reads : 

     `9999.9   VS_RtTq      - Rated generator torque/constant generator torque in Region 3 for simple variable-speed generator control (HSS side) `

So if we are supposed to use 1/4th of this value, I expected to use MaxTorqueRate = 10000 N.m/s, but in the file you have modified you specified 1000000 N.m/s, can you please explain me the difference ? 

Best regards, 

Maximilien

**Comment by dzalkind** [comment]
I think your value is correct.  I started to make the changes, but then realized that I also needed to account for the gearbox ratio as you suggest.  Thanks!

Dan

**Comment by MaximilienAndre** [comment]
Dear @dzalkind , thank you for your confirmation. I needed to make sure before tuning it for the DTU-10MW which compared to the IEA-10MW has a gearbox. 

Best regards, 

Maximilien
