### ISSUE TITLE
Pitch control start point

### ISSUE THREAD

**Issue by GBA217** [NREL/ROSCO#382]
Hello,

I'm working on a wind turbine model in which the rotor speed saturates to the rated value before the rotor torque. I'm using the lidiscon dll compiled from the latest ROSCO controller available. I would like to know how I can make the pitch control start only after the rated torque is achieved rather than it starting right after rated speed is reached. (IPC is inactive)
I understand  PC_RefSpd defines the speed at which the pitch control should start. But how do I make the turbine pitch only after reaching the rated torque value?	
![image](https://github.com/user-attachments/assets/a4c6504c-24da-4f61-9273-222e64ca913b)

TIA

**Comment by dzalkind** [comment]
First, I would ensure that you're disabling peak shaving with `PS_Mode` of 0.

Then, you can decrease `TSR_Operational` in the tuning yaml to create a low speed set point for the torque control.  This may not be aerodynamically optimal, but it should keep the torque low compared to the rotor/generator speed.
