### ISSUE TITLE
Why is the `tune_ROSCO.py` file not found?

### ISSUE THREAD

**Issue by SYZ622** [NREL/ROSCO#383]
When I run openfast 3.5.3, it prompts me that I should compile the controller, so I installed and downloaded the ROSCO 2.9.2 controller, but when I read the documentation for its use, I found several references to the `tune_ROSCO.py` file, which I didn't find inside the folder, so I hope to get some help!

**Comment by dzalkind** [comment]
Thanks for making us aware of this.  This part of the documentation is out of date.  Most of the `tune_ROSCO.py` features have been moved here: https://github.com/NREL/ROSCO/blob/main/rosco/toolbox/tune.py

This example shows the basics of DISCON tuning: https://github.com/NREL/ROSCO/blob/main/Examples/03_tune_controller.py
