### ISSUE TITLE
Error in ROSCO.mdl with Simulink

### ISSUE THREAD

**Issue by lweidsab** [NREL/ROSCO#387]
Hi Dan,

I am also have an issue when I run ROSCO.mdl from Simulink package.  I attached it as follows. I was wondering whether it can be solved?

>> runFAST
26  addpath('Utilities')
29  [Param,Cx] = ReadWrite_FAST(fast);
GetFASTPar:: Parameter F_NotchType not found.
Error using runFAST (line 59)
Multiple errors occurred.
Causes:
    Error using runFAST (line 59)
    Syntax error in expression 'u(strmatch('Azimuth',OutList))' in 'ROSCO/Cyclic Pitch controller/extract Azimuth'.
    Error using runFAST (line 59)
    Syntax error in expression 'u(strmatch('BldPitch1',OutList))' in 'ROSCO/Extract Signals/Extract BldPitch1'.
    Error using runFAST (line 59)
    Error in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function': S-Function 'FAST_SFunc' does not exist.
    Error using runFAST (line 59)
    Syntax error in expression 'u(strmatch('BldPitch1',OutList))' in 'ROSCO/Monitor/Extract BldPitch1'.

Another question is that I see in the forum is that this simulink repository is currently not updated. Could you please give an answer? As for the IPC module, the interface is useable or not? Look forward to hear from you. Thanks

**Comment by dzalkind** [comment]
Hi, please search previous Github questions/issues about Matlab/Simulink.  That error looks like others that have been raised.  All the modules should be usable, but we can't guarantee it and you should verify its functionality.

**Comment by lweidsab** [comment]
![image](https://github.com/user-attachments/assets/943f5202-5f67-46ca-afef-9016645e4efc)
Thanks a lot, I met a new error list as follows.

**Comment by lweidsab** [comment]
![image](https://github.com/user-attachments/assets/f409a3cf-39ef-4dd8-9112-b77c5da1b16d)
![image](https://github.com/user-attachments/assets/41c3da8e-6a43-4ec9-a4d9-69773caaa7dd)
I checked the bug history and made some change sone the S-function, yet it doesn't work at all. Look forward to your comments. Thanks indeed.

**Comment by dzalkind** [comment]
I recommend looking at the OpenFAST repository: https://github.com/OpenFAST/openfast/tree/main/glue-codes/simulink

Since this part of the repository is not currently supported, I can't provide any further guidance.
