### ISSUE TITLE
64 bit DLL load in Simpack

### ISSUE THREAD

**Issue by JayceeYJ** [NREL/ROSCO#67]
The complied 64 bit NREL 5-MW reference controller load in simpack can run well，but the complied 64 bit ROSCO controller libdiscon.dll cannot calculate in simpack 2019.
The input file Cp_Ct_Cq.NREL5MW.txt with DISCON.IN in same foleder or with libdiscon.dll?

**Comment by dzalkind** [comment]
Things work best when you call simpack or openfast from the same directory as all the input files, including the Cp file.  Another good option is to use absolute paths in the filename.  I hope this helps.

**Comment by dzalkind** [comment]
Did this resolve the issue you were having?

I'm not sure how much support we can provide without an example or error message.
