### ISSUE TITLE
libdiscon file for IEA15MW UMaine Semi-Sub Model

### ISSUE THREAD

**Issue by QusayHawari** [NREL/ROSCO#75]
Hi, 

I am operation on MACOS, and I wanted to ask about the libdiscon file for the IEA15MW-UMaine found in 
https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST/IEA-15-240-RWT-UMaineSemi/ServoData 

Is there a libdiscon.dylib 64-bit that I can use as there's only the .so, and .dll files?

I tried to generate it using cmake .. , but I ran through the following error!

Thanks in Advance,
Qusay.

---------------------------------------------------------------
 % cd ROSCO
 ROSCO % mkdir build
mkdir: build: File exists
% cd build
% cmake ..
-- The Fortran compiler identification is Intel 19.1.3.20200925
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: /usr/local/bin/ifort
-- Check for working Fortran compiler: /usr/local/bin/ifort - broken
CMake Error at /usr/local/Cellar/cmake/3.21.3_1/share/cmake/Modules/CMakeTestFortranCompiler.cmake:54 (message):
  The Fortran compiler

    "/usr/local/bin/ifort"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/qusayhawari/ROSCO/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/gmake -f Makefile cmTC_9534e/fast && /usr/local/bin/gmake  -f CMakeFiles/cmTC_9534e.dir/build.make CMakeFiles/cmTC_9534e.dir/build
    gmake[1]: Entering directory '/Users/qusayhawari/ROSCO/build/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_9534e.dir/testFortranCompiler.f.o
    /usr/local/bin/ifort    -c /Users/qusayhawari/ROSCO/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_9534e.dir/testFortranCompiler.f.o
    Linking Fortran executable cmTC_9534e
    /usr/local/Cellar/cmake/3.21.3_1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9534e.dir/link.txt --verbose=1
    /usr/local/bin/ifort CMakeFiles/cmTC_9534e.dir/testFortranCompiler.f.o -o cmTC_9534e 
    ld: library not found for -lSystem
    gmake[1]: *** [CMakeFiles/cmTC_9534e.dir/build.make:99: cmTC_9534e] Error 1
    gmake[1]: Leaving directory '/Users/qusayhawari/ROSCO/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_9534e/fast] Error 2
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/qusayhawari/ROSCO/build/CMakeFiles/CMakeOutput.log".
See also "/Users/qusayhawari/ROSCO/build/CMakeFiles/CMakeError.log".
qusayhawari@wireless-staff-pt3-119-81 build %

**Comment by dzalkind** [comment]
Hi @QusayHawari,

[Here](https://github.com/NREL/ROSCO/releases/tag/v2.3.0) are the binaries for the latest release of ROSCO.  You can also download/install them using conda as described [here](https://rosco-toolbox.readthedocs.io/en/latest/source/install.html).

If you still want to compile yourself, it looks like there is something wrong with your Fortran compiler; [this](https://openfast.readthedocs.io/en/main/source/install/index.html#cmake-with-make-for-linux-macos) could be a helpful reference.

I hope this helps!

Best, Dan

**Comment by rafmudaf** [comment]
Hi @QusayHawari - the [conda-forge](https://anaconda.org/conda-forge/rosco) listing for ROSCO indicates there is a 64-bit macOS installer. Are you sure you need to recompile?

@dzalkind will the yaml input file in the repo referenced above work for the latest version of ROSCO?
